### ISSUE TITLE
False positives on inheritance

### ISSUE THREAD

**Issue by luizkowalski** [rubocop/rubocop-thread_safety#12]
hello! 👋🏻 

I'm seeing something that I believe might be a false positive.

I have a base class with some instance and class methods that other classes inherit from. The class methods are used to configure behavior for the class, like, will be wrapped in a transaction or not, something very similar to this

```ruby
class Parent
  class << self
    def set(val)
      puts "Value: #{val}; #{Thread.current.object_id}"
      @val = val
      puts "Setting value to #{@val}; #{Thread.current.object_id}"
    end

    attr_reader :val
  end
end

class Children1 < Parent
  set(true)

  def initialize
    puts "Val for Children1: #{self.class.val}"
  end
end

class Children2 < Parent
  set(false)

  def initialize
    puts "Val for Children2: #{self.class.val}"
  end
end
```

The cop tells me that I have an offense at `Parent` but that doesn't seem like it:

```console
irb(main):060:0> Thread.new { Children1.new }; Thread.new { Children2.new }
=> #<Thread:0x000000010b770ce8 (irb):60 run>
Value: true; 463920
Setting value to true; 463920
Val for Children1: true
Value: false; 463940
Setting value to false; 463940
Val for Children2: false
irb(main):061:0> Thread.new { Children1.new }; Thread.new { Children2.new }
=> #<Thread:0x000000010b823708 (irb):61 run>
Val for Children1: true
Val for Children2: false
irb(main):062:0> Thread.new { Children1.new }; Thread.new { Children2.new }
=> #<Thread:0x000000010b8d8d60 (irb):62 run>
Val for Children1: true
Val for Children2: false
```

The first time the different threads instantiate the children, `set` is called and set `val` at the `Children` level. Subsequent calls do not do it anymore and `self.class.val` returns the expected result. 

To be honest, I don't know if this is really a false positive. Seems like the exact intended outcome since Rubocop doesn't know where this class will be used and/or will be inherited. I guess my question is: is it safe to ignore this cop in this specific class and case?

**Comment by mikegee** [comment]
I agree with your analysis. The example code doesn't look like there is a threading problem to me. 

The pattern that I have noticed is this kind of code is thread-safe when it is invoked at boot-time, but not thread-safe when invoked at run-time. Since you're calling `set(true)` and `set(false)` in the children classes while they are being loaded, that should always be safe. The cop can't know about all the callsites, so it can't know that this is safe usage.

**Comment by luizkowalski** [comment]
great, thanks for replying and confirming it! I will close this one

**Comment by luizkowalski** [comment]
great, thanks for replying and confirming it! I will close this one
