### ISSUE TITLE
Clarify `class_attribute` thread safety

### ISSUE THREAD

**Issue by viralpraxis** [rubocop/rubocop-thread_safety#34]
Follow-up from https://github.com/covermymeds/rubocop-thread_safety/issues/54

Could someone please clarify if `class_attribute` is thread-safe now?

**Comment by mikegee** [comment]
I've look at https://github.com/rails/rails/pull/29233 before because a coworker thought `class_attribute` was thread-safe these days too. I can't follow how that work fixed the thread-safety problem. We're gonna need someone smarter to help.

**Comment by viralpraxis** [comment]
Well, as far as I understand, the problem was that previous AS `class_attribute` implementation used [thread-unsafe](https://bugs.ruby-lang.org/issues/13574#note-4) "`undef_method` + `define_method`" approach. It was thread-unsafe because thread switch (between threads trying to mutate class attribute) could happen after `undef_method` and before `define_method`. The PR I mentioned replaced it with [atomic]( https://lifegoo.pluskid.org/upload/doc/yarv/yarv_iset.html#detail-38) `define_method`: https://github.com/rails/rails/blob/2b0ae167eee81d0d31b1d2f88c3f6c596c61ea8c/activesupport/lib/active_support/core_ext/module/redefine_method.rb#L17-L22

An MRE:

```ruby
# test.rb

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activesupport', ENV.fetch("AS_VERSION"), require: false
end

require "active_support"
require "active_support/core_ext/class/attribute"

class Foo
  class_attribute :bar
end

puts RUBY_DESCRIPTION

Thread.abort_on_exception = true

Array
  .new(1000) { |i| Thread.new { Foo.bar = i } }
  .each(&:join)
```
Running on JRuby with `activesupport=4.0.0`:

```
$ AS_VERSION=4.0.0 ruby test.rb
jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 20.0.2+9 on 20.0.2+9 +jit [x86_64-linux]
warning: thread "Ruby-0-Thread-2: test.rb:21" terminated with exception (report_on_exception is true):
NameError: undefined method `bar' for class `Foo'
            undef_method at org/jruby/RubyModule.java:3674
  remove_possible_method at /home/viralpraxis/.asdf/installs/ruby/jruby-9.4.8.0/lib/ruby/gems/shared/gems/activesupport-4.0.0/lib/active_support/core_ext/module/remove_method.rb:4
         class_attribute at /home/viralpraxis/.asdf/installs/ruby/jruby-9.4.8.0/lib/ruby/gems/shared/gems/activesupport-4.0.0/lib/active_support/core_ext/class/attribute.rb:86
             module_eval at org/jruby/RubyModule.java:3684
             module_eval at org/jruby/RubyModule.java:3715
         class_attribute at /home/viralpraxis/.asdf/installs/ruby/jruby-9.4.8.0/lib/ruby/gems/shared/gems/activesupport-4.0.0/lib/active_support/core_ext/class/attribute.rb:85
                  <main> at test.rb:21
warning: thread "Ruby-0-Thread-126: test.rb:21" terminated with exception (report_on_exception is true):
```

Running on JRuby with `activesupport=7.0.0`:

```shell
$ AS_VERSION=7.0.0 ruby test.rb && echo $?
jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 20.0.2+9 on 20.0.2+9 +jit [x86_64-linux]
0
```

It's also mentioned that this issue is not reproducible on MRI -- probably due to difference between MRI and JVM schedulers.

**Comment by mikegee** [comment]
Thanks @viralpraxis! That is a convincing analysis.

I would accept a PR that removes `class_attribute` offenses, if you want to take care of it.

**Comment by viralpraxis** [comment]
Hey @mikegee, could you please trigger the CI?

**Comment by viralpraxis** [comment]
Actually, it might be that I was too fast with this one. While it's true that `class_attribute` does not raise runtime errors nowadays, the original intention was to [simply prohibit its usage because it *might* lead to thread-safety-related issues if used incorrectly](https://github.com/covermymeds/rubocop-thread_safety/pull/24).

I think we should bring it back **but** add Cop configratuin option (e.g. `AllowActiveSupportClassAttribute: false`). If class attributes are set at boot-time and are immutable nothing bad should happen.

FYI @mikegee

**Comment by viralpraxis** [comment]
To elaborate on my point: the only reason I didn't add `rubocop-thread_safety` years before is that because each time I tried there were many offenses about `class_attribute` which could not be ignored without disabling the entire cop or placing `rubocop:disable` everywhere. I think optional check `class_attribute` check would be good.
